export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-blue-50 dark:from-gray-900 dark:via-purple-900 dark:to-indigo-900">
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl p-8 md:p-12">
          <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 bg-clip-text text-transparent mb-6">
            Terms &amp; Conditions
          </h1>

          <p className="text-gray-600 dark:text-gray-400 mb-8">
            Last updated: December 8, 2025
          </p>

          <div className="space-y-8 text-gray-700 dark:text-gray-300">
            {/* 1. Agreement to Terms */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                1. Agreement to terms
              </h2>
              <p className="leading-relaxed">
                These Terms &amp; Conditions (<strong>&quot;Terms&quot;</strong>) govern your
                access to and use of the BNG Baby Names website at{' '}
                <span className="font-mono text-sm">
                  https://babynamegenerator.xyz
                </span>{' '}
                (the <strong>&quot;Site&quot;</strong>) and all related tools, features
                and content (collectively, the <strong>&quot;Service&quot;</strong>).
                By accessing or using the Service, you agree to be bound by these Terms.
                If you do not agree, you must not use the Service.
              </p>
            </section>

            {/* 2. Our Service */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                2. About the service
              </h2>
              <p className="leading-relaxed mb-3">
                BNG Baby Names provides an AI-powered baby name generator, domain search
                links, and curated baby product recommendations. The Service is
                intended solely for informational and inspirational purposes to help
                parents and guardians explore potential baby names and related products.
              </p>
              <p className="leading-relaxed">
                The Service does <strong>not</strong> provide medical, legal,
                religious, or professional advice. Any decisions you make based on
                the content generated by the Service are your sole responsibility.
              </p>
            </section>

            {/* 3. Eligibility */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                3. Eligibility
              </h2>
              <p className="leading-relaxed">
                The Service is intended for use by individuals who are at least 18
                years old or the age of majority in their jurisdiction. By using the
                Service, you represent that you meet this requirement and that you
                have the legal capacity to enter into these Terms.
              </p>
            </section>

            {/* 4. Use of Service */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                4. Use of the Service
              </h2>

              <div className="space-y-4">
                <div>
                  <h3 className="text-xl font-semibold text-gray-800 dark:text-white mb-2">
                    4.1 Permitted use
                  </h3>
                  <p className="leading-relaxed">
                    You may use the Service for personal, non-commercial purposes to
                    explore and manage baby name ideas, check domains, and view product
                    recommendations. You agree to use the Service in compliance with
                    all applicable laws and regulations.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-semibold text-gray-800 dark:text-white mb-2">
                    4.2 Prohibited activities
                  </h3>
                  <p className="leading-relaxed mb-2">
                    You agree that you will <strong>not</strong>:
                  </p>
                  <ul className="list-disc list-inside ml-4 space-y-1">
                    <li>Use the Service for any unlawful, harmful, or fraudulent purpose</li>
                    <li>
                      Attempt to gain unauthorised access to the Site, servers, or networks
                    </li>
                    <li>Interfere with or disrupt the operation of the Service</li>
                    <li>
                      Use automated tools (scrapers, bots, etc.) to access or query the
                      Service in a way that places unreasonable load on our systems
                    </li>
                    <li>
                      Copy, modify, distribute, or create derivative works of the Service
                      or its content except as explicitly allowed by these Terms
                    </li>
                    <li>
                      Reverse engineer, decompile, or attempt to extract source code or
                      models used by the Service
                    </li>
                  </ul>
                </div>
              </div>
            </section>

            {/* 5. AI & Pronunciation */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                5. AI-generated content &amp; pronunciation
              </h2>
              <p className="leading-relaxed mb-3">
                The Service uses artificial intelligence and third-party APIs to
                generate baby name suggestions, descriptions, and sometimes explanations
                of meanings or origins. It may also use text-to-speech providers (such
                as ElevenLabs and browser speech synthesis) to provide pronunciation
                audio for names.
              </p>
              <p className="leading-relaxed mb-3">
                While we make reasonable efforts to provide helpful and culturally
                sensitive suggestions, AI-generated content can be incomplete,
                outdated, biased, or inaccurate. Pronunciations may vary based on
                accent, language, and region.
              </p>
              <p className="leading-relaxed">
                You should independently verify any information (including meanings,
                religious or cultural suitability, numerology, or pronunciation) and
                consult with family, community, or religious advisors before making a
                final naming decision.
              </p>
            </section>

            {/* 6. Affiliates & Third-Party Links */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                6. Affiliates and third-party links
              </h2>
              <p className="leading-relaxed mb-3">
                The Site may contain links to third-party websites or services,
                including but not limited to Amazon, Namecheap, and other retailers
                or partners. Some of these links are <strong>affiliate links</strong>,
                meaning we may earn a commission if you click the link or make a
                purchase, at no additional cost to you.
              </p>
              <p className="leading-relaxed mb-3">
                We do not own or control third-party websites and are not responsible
                for their content, products, policies, or practices. Your use of any
                third-party site is solely between you and that provider, and is
                governed by their own terms and privacy policies.
              </p>
              <p className="leading-relaxed">
                Inclusion of any link on the Site does not imply endorsement or
                recommendation of the third-party website, service, or product.
              </p>
            </section>

            {/* 7. Intellectual Property */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                7. Intellectual property
              </h2>
              <p className="leading-relaxed mb-3">
                The Site, including its design, branding, layout, text, graphics,
                logos, icons, and underlying code, is owned or licensed by BNG Baby
                Names and is protected by applicable copyright, trademark, and other
                intellectual property laws.
              </p>
              <p className="leading-relaxed">
                Baby names themselves, cultural naming traditions, and short factual
                descriptions are generally not protected by copyright. You are free to
                use any suggested names for personal purposes. However, you may not
                copy large portions of the Site&apos;s content or interface for use in
                a competing service without our prior written permission.
              </p>
            </section>

            {/* 8. No Professional Advice */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                8. No professional or religious advice
              </h2>
              <p className="leading-relaxed">
                Content on the Site is provided for inspiration and informational
                purposes only and does not constitute medical, legal, financial,
                religious, or professional advice. Naming decisions can have cultural,
                religious, or legal implications. You are solely responsible for
                evaluating and confirming whether a name is appropriate for your
                family, culture, faith, or jurisdiction.
              </p>
            </section>

            {/* 9. Disclaimer of Warranties */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                9. Disclaimer of warranties
              </h2>
              <p className="leading-relaxed mb-3">
                The Service is provided on an <strong>&quot;AS IS&quot;</strong> and{' '}
                <strong>&quot;AS AVAILABLE&quot;</strong> basis, without warranties of
                any kind, whether express or implied. To the fullest extent permitted
                by law, we disclaim all warranties, including but not limited to:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-1">
                <li>Any implied warranties of merchantability or fitness for a purpose</li>
                <li>Any warranty that the Service will be uninterrupted, secure, or error-free</li>
                <li>
                  Any warranty regarding the accuracy, reliability, or completeness of
                  AI-generated names, meanings or pronunciations
                </li>
                <li>
                  Any warranty that the Service will meet your expectations or specific
                  requirements
                </li>
              </ul>
            </section>

            {/* 10. Limitation of Liability */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                10. Limitation of liability
              </h2>
              <p className="leading-relaxed mb-3">
                To the maximum extent permitted by law, BNG Baby Names and its owners,
                contributors, and affiliates shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages, or any loss of
                profits, revenue, data, or goodwill, arising out of or in connection
                with your use of (or inability to use) the Service.
              </p>
              <p className="leading-relaxed">
                In no event shall our total aggregate liability for all claims relating
                to the Service exceed the amount you paid to use the Service in the
                3 months immediately preceding the claim (which is typically ₹0, as the
                Service is currently offered free of charge).
              </p>
            </section>

            {/* 11. Changes to Service & Terms */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                11. Changes to the Service and these Terms
              </h2>
              <p className="leading-relaxed mb-3">
                We may update, modify, or discontinue any part of the Service at any
                time, with or without notice, including features, content, and
                availability.
              </p>
              <p className="leading-relaxed">
                We may also update these Terms from time to time. When we do, we will
                change the &quot;Last updated&quot; date at the top of this page. Your
                continued use of the Service after any changes constitutes your
                acceptance of the revised Terms.
              </p>
            </section>

            {/* 12. Governing Law */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                12. Governing law &amp; jurisdiction
              </h2>
              <p className="leading-relaxed">
                These Terms shall be governed by and construed in accordance with the
                laws of India, without regard to its conflict of law principles. Any
                disputes arising out of or in connection with these Terms or the
                Service shall be subject to the exclusive jurisdiction of the courts
                located in Lucknow, Uttar Pradesh, India.
              </p>
            </section>

            {/* 13. Contact */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">
                13. Contact information
              </h2>
              <p className="leading-relaxed">
                If you have any questions or concerns about these Terms or the
                Service, please contact us:
              </p>
              <div className="mt-4 p-4 bg-indigo-50 dark:bg-indigo-900/20 rounded-lg">
                <p className="font-semibold text-indigo-600 dark:text-indigo-400">
                  Email: hello@babynamegenerator.xyz
                </p>
                <p className="text-gray-600 dark:text-gray-400 mt-1 text-sm">
                  Please include &quot;Terms&quot; in the subject line so we can route
                  your message correctly.
                </p>
              </div>
            </section>

            {/* Acceptance */}
            <section className="border-t border-gray-200 dark:border-gray-700 pt-6">
              <p className="leading-relaxed font-semibold text-gray-800 dark:text-white">
                By using BNG Baby Names, you acknowledge that you have read,
                understood, and agree to be bound by these Terms &amp; Conditions.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
